### ISSUE TITLE
Train taxonomic assignment models from FASTA within freyr

### ISSUE THREAD

**Issue by alexpiper** [AVR-biosecurity-bioinformatics/freyr#15]
I think it would be good to have an option to train a new IDTAXA (or any other classifier we end up using) model if only a FASTA file is provided. This will make freyr more self contained, and allow users to easily add / remove sequences from their reference databases easily themselves.

While training can take hours on a large FASTA file, its much quicker on smaller in-house databases, and if run in parallel to the other processes may be complete before the rest of the pipeline gets up to taxonomic assignment step that requires this model. If the trained model is one of the outputs, the user could then re-use this in future runs

The [train_idtaxa](https://github.com/alexpiper/taxreturn/blob/master/R/tax_utilities.R) function from taxreturn could be brought over to freyr to handle this.

Including this in freyr doesnt affect the use-case for the companion mimir pipleine, which should be about curating sequences for inclusion into reference databases

**Comment by jackscanlan** [comment]
This would be pretty easy to do, could just create a `TRAIN_IDTAXA` module that runs if the `idtaxa_db` field in the loci params file is `NA`. Would have to be careful with how the resulting output model is merged back into the channels that hold the `loci_params` data though.

**Comment by jackscanlan** [comment]
Implemented for `IDTAXA` in 611b7b0; can add additional training modules when alternative taxonomic assignment tools are added
