### ISSUE TITLE
Resolve duplicated functions.R files

### ISSUE THREAD

**Issue by alexpiper** [AVR-biosecurity-bioinformatics/freyr#7]
Currently functions.R is duplicated in the R directory and bin directory. We should delete one to avoid duplication. I keep mistakenly editing the R/functions.R, while its the bin/functions.R that sourced in freyr 😅 

Not sure on the nextflow convention on where should sourced functions should reside. It may be easier to find if kept seperate to the 'executable' R scripts in bin?

**Comment by jackscanlan** [comment]
I agree we should delete one -- I've been adding to the `bin/functions.R` as this is the one that gets sourced in the `bin/process_start.R` script. I believe the convention is to add all sourced scripts to `./bin` but I actually can't find any mention of this in the Nextflow docs! 

The `./R` folder probably doesn't need to exist anymore, though, as I don't believe there's anything in there that is currently used by the pipeline (there's a copy of `themes.R` in `./bin` too).

**Comment by alexpiper** [comment]
Removing `./R` sounds good to me
